archives:
  mgmt-letter-11-08:
    description: "In 2011, the National Archives' IG wrote management,
    baffled about the fact that its electronic records system, ERA, had
    no full text search, even after giving Lockheed Martin a 6-year,
    $430M contract."
    author: Eric Mill
    author_link: "https://twitter.com/konklone"
commerce:
  13-1077:
    description: "The US Patent Office's board of appeals wasted $5 million
    since 2009 by paying people to do nothing, as the nation's patent backlog
    continued rising. Senior management knew of this and allowed it to
    continue."
    author: Eric Mill
    author_link: "https://twitter.com/konklone"
doj:
  s-2016-e1606:
    description: "The DOJ IG reviewed privately operated prisons that have
    contracts with the Federal Bureau of Prisons. The privately owned prisons
    had significantly higher rates of safety and security incidents, and BOP
    oversight of the prisons was lacking. One week later, DOJ announced plans
    to end use of privately operated prisons."
    author: David Cook
    author_link: "https://twitter.com/divergentdave"
  s-2017-e1702:
    description: "The DOJ OIG reviewed oversight of civil forfeiture across
    the DOJ. It found there was a lack of oversight, both with respect to
    achieving law enforcement goals and protection of civil liberties. The
    DEA's practices were particularly concerning, because many cash seizures
    weren't linked to any investigation or prosecution."
    author: David Cook
    author_link: "https://twitter.com/divergentdave"
epa:
  17-P-0004:
    description: "The EPA's OIG found that EPA Region 5 should have intervened
    sooner in the Flint, MI water crisis. Since Michigan's actions failed to
    protect the public, the Safe Drinking Water Act gave the EPA the authority
    to issue an emergency order, though they didn't do so until seven months
    later."
    author: David Cook
    author_link: "https://twitter.com/divergentdave"
